Implement shellcheck hints and other improvements

diff --git a/bt-iso b/bt-iso
--- a/bt-iso
+++ b/bt-iso
@@ -9,13 +9,13 @@
 # option) any later version.
 
 
-fatal() { echo "FATAL [$(basename $0)]: $@" 1>&2; exit 1; }
-warning() { echo "WARNING [$(basename $0)]: $@"; }
-info() { echo "INFO [$(basename $0)]: $@"; }
+fatal() { echo "FATAL [$(basename "$0")]: $*" 1>&2; exit 1; }
+warning() { echo "WARNING [$(basename "$0")]: $*"; }
+info() { echo "INFO [$(basename "$0")]: $*"; }
 
 usage() {
     cat<<EOF
-Syntax: $(basename $0) [--publish | -u] [-n] [-s] appname
+Syntax: $(basename "$0") [--publish | -u] [-n] [-s] appname
 Builds appliance appname (e.g., core) ISO
 
 Arguments::
@@ -46,7 +46,7 @@ Environment::
 
 EOF
     if [[ "$#" -ne 0 ]]; then
-        echo "Error: $@"
+        echo "Error: $*"
         exit 1
     fi
     exit
@@ -56,16 +56,17 @@ clone_or_pull() {
     # If $dir doesn't exist, clone $repo. If it does, update from origin master
     dir=$1
     repo=$2
-    [[ -n "$dir" ]] && [[ -n "$repo" ]] \
-        || fatal "One or more empty values passed to function: $FUNCNAME."
-    if [ ! -e $dir ]; then
+    if [[ -z "$dir" ]] || [[ -z "$repo" ]]; then
+        fatal "One or more empty values passed to function: ${FUNCNAME[*]}."
+    fi
+    if [ ! -e "$dir" ]; then
         info "Attempting to clone repo $repo to $dir."
-        cd $(dirname $dir)
-        git clone https://github.com/$repo $dir
-        cd $dir
+        cd "$(dirname "$dir")"
+        git clone "https://github.com/$repo" "$dir"
+        cd "$dir"
     else
         info "Repo $repo found, attempting to update"
-        cd $dir
+        cd "$dir"
         git pull origin master
     fi
 }
@@ -75,21 +76,22 @@ get_version() {
     sp="[[:space:]]"
     pkg_info=$(dpkg -l \
         | sed -En "s|^ii.*($pkg)$sp*([0-9a-z\.-:]*)$sp*amd64$sp*.*|\1 \2|p")
-    echo $pkg_info | cut -d' ' -f2
+    echo "$pkg_info" | cut -d' ' -f2
 }
 
 git_unshallow() {
     local dir=$1
     local branch=$2
     # find remote name for turnkey repo
-    local remote=$(\
+    remote=$(\
         sed -En '\|github.com.turnkeylinux.*fetch\)$| s|([a-z]*)\s.*|\1|p' \
-        <<<$(git remote -v))
-    cd $dir
+        <<<"$(git remote -v)")
+    local "remote"
+    cd "$dir"
     if [[ "$(git symbolic-ref --short HEAD)" != "$branch" ]]; then
         git remote set-branches "$remote" '*'
         git fetch "$remote" --unshallow 2>/dev/null || git fetch "$remote"
-        git checkout $branch || git checkout $branch-dev
+        git checkout "$branch" || git checkout "$branch-dev"
     fi
     cd -
 }
@@ -111,12 +113,12 @@ get_codename() {
 }
 
 container_status() {
-    podman container inspect $1 --format "{{.State.Status}}"
+    podman container inspect "$1" --format "{{.State.Status}}"
 }
 
 export WEBDRIVER_CONNECT_ATTEMPTS=${WEBDRIVER_CONNECT_ATTEMPTS:-200}
 export WEBDRIVER_CONNECT_TIMEOUT=${WEBDRIVER_CONNECT_TIMEOUT:-5}
-ARGS="$@"
+ARGS="$*"
 unset no_screens use_existing appname skip_setup TKL_CODENAME
 while [[ "$1" != "" ]]; do
     case $1 in
@@ -149,13 +151,15 @@ if [[ -z "$no_screens" ]]; then
             clicksnap_mod=gitlab
             ;;
         *)
-            clicksnap_mod=$(sed "s|-|_|g" <<<$appname);;
+            clicksnap_mod="${appname//-/_}";;
     esac
 fi
 
-export BT=$(dirname $(readlink -f $0))
-export BT_CONFIG=$BT/config
-. $BT_CONFIG/common.cfg
+link=$(readlink -f "$0")
+BT=$(dirname "$link")
+export BT
+export BT_CONFIG="$BT/config"
+. "$BT_CONFIG/common.cfg"
 
 if [[ "$publish" == "yes" ]]; then
     unset msg
@@ -165,29 +169,29 @@ if [[ "$publish" == "yes" ]]; then
     [[ -n "$BT_PUBLISH_PROFILES" ]] || fatal "BT_PUBLISH_PROFILES not set"
     [[ -z "$use_existing" ]] || usage "conflicting options: --publish / -u|--use-existing"
     [[ -z "$skip_setup" ]] || usage "conflicting options: --publish / -s|--skip-setup"
-    which aws >/dev/null || $BT/bin/aws-setup --awscli
+    which aws >/dev/null || "$BT"/bin/aws-setup --awscli
 else
     warning "--publish was not specified"
 fi
 
-cd $BT
+cd "$BT"
 BASE_DIR=/turnkey/public
 COMMIT_ID=$(git rev-parse --short HEAD)
 if [[ -z "$skip_setup" ]]; then
     # Leverage tkldev-setup to ensure important repos are cloned and at latest
     # commit; also ensures RELEASE & ARCH are set.
-    tkldev-setup $appname \
+    tkldev-setup "$appname" \
         || warning "tkldev-setup failed. Attempting to continue anyway."
 
     # unless -n|--no-screens set up clicksnap and check for clicksnap file
     if [[ -z "$no_screens" ]]; then
         if [[ ! -f /root/clicksnap-setup.done ]]; then
             info "Setting up clicksnap and dockerize"
-            $BT/bin/clicksnap-setup $appname
+            "$BT"/bin/clicksnap-setup "$appname"
             touch /root/clicksnap-setup.done
         else
             setup_time=$(date -r /root/clicksnap-setup.done +%s)
-            allowed_age=$(( $setup_time + 86400 )) # 24 hours
+            allowed_age=$(( setup_time + 86400 )) # 24 hours
             if [[ $allowed_age -lt $(date +%s) ]]; then
                 info "Attempting clicksnap update"
                 clone_or_pull $BASE_DIR/clicksnap turnkeylinux/clicksnap
@@ -196,8 +200,7 @@ if [[ -z "$skip_setup" ]]; then
                 cd -
                 touch /root/clicksnap-setup.done
             fi
-            if ! ls $BASE_DIR/clicksnap/src/apps/ \
-                    | grep -q -w "$clicksnap_mod"; then
+            if ! [[ $clicksnap_mod == "*$BASE_DIR/clicksnap/src/apps/*" ]]; then
                 # double check that it doesn't reuse another module
                 if ! grep -q "^    h.insert(\"$clicksnap_mod\", Box::new(" \
                         $BASE_DIR/clicksnap/src/apps/mod.rs; then
@@ -213,22 +216,23 @@ if [[ -z "$skip_setup" ]]; then
     # attempt to download the right bootstrap; otherwise build it
     TKL_HOST_VER=$(turnkey-version -t | cut -d. -f1)
     TKL_BUILD_VER=$(sed -nE "1s|turnkey-[a-z0-9-]*-([0-9]+).*|\1|p" \
-        $BT_PRODUCTS/$appname/changelog)
+        "$BT_PRODUCTS/$appname/changelog")
     if [[ "$TKL_HOST_VER" != "$TKL_BUILD_VER" ]]; then
         warning "Host TKL version ($TKL_HOST_VER) does not match guest version" \
                 " ($TKL_BUILD_VER)"
         unset TKL_CODENAME
-        get_codename $TKL_BUILD_VER
+        get_codename "$TKL_BUILD_VER"
         export RELEASE=debian/$TKL_CODENAME
         git_unshallow "/turnkey/buildtasks" "$TKL_BUILD_VER.x"
         # if buildtasks has changed, restart bt-iso
-        cd $BT
+        cd "$BT"
         if [[ "$(git rev-parse --short HEAD)" != "$COMMIT_ID" ]]; then
-            exec ./$(basename $0) $ARGS
+            exec ./"$(basename "$0")" "$ARGS"
             exit
         fi
         cd -
         git_unshallow "$FAB_PATH/common" "$TKL_BUILD_VER.x"
+        # TODO KEY unused!?
         KEY=$FAB_PATH/common/keys/tkl-$TKL_CODENAME-images.asc
         IMAGES="http://mirror.turnkeylinux.org/turnkeylinux/images"
         BOOTSTRAP_NAME="bootstrap-$TKL_CODENAME-$(dpkg --print-architecture)"
@@ -236,49 +240,49 @@ if [[ -z "$skip_setup" ]]; then
 
         if [[ ! -d "$BOOTSTRAP_PATH" ]]; then
             info "Attempting to download $BOOTSTRAP_NAME"
-            mkdir -p $(dirname $BOOTSTRAP_PATH)
-            cd $(dirname $BOOTSTRAP_PATH)
+            mkdir -p "$(dirname "$BOOTSTRAP_PATH")"
+            cd "$(dirname "$BOOTSTRAP_PATH")"
             exit_code=0
-            wget -nc $IMAGES/bootstrap/$BOOTSTRAP_NAME.tar.gz || exit_code=$?
-            wget -nc $IMAGES/bootstrap/$BOOTSTRAP_NAME.tar.gz.hash || exit_code=$?
+            wget -nc $IMAGES/bootstrap/"$BOOTSTRAP_NAME.tar.gz" || exit_code=$?
+            wget -nc $IMAGES/bootstrap/"$BOOTSTRAP_NAME.tar.gz.hash" || exit_code=$?
             if [[ "$exit_code" -eq 0 ]]; then
                 info "verifying $BOOTSTRAP_NAME"
                 TMP_KEYRING="$(mktemp -d)/tmp.gpg"
                 GPG="gpg --no-default-keyring --keyring $TMP_KEYRING"
-                $GPG --import $FAB_PATH/common/keys/tkl-$TKL_CODENAME-images.asc
-                $GPG --verify $BOOTSTRAP_NAME.tar.gz.hash
+                $GPG --import "$FAB_PATH/common/keys/tkl-$TKL_CODENAME-images.asc"
+                $GPG --verify "$BOOTSTRAP_NAME.tar.gz.hash"
 
                 info "unpacking $BOOTSTRAP_NAME"
-                mkdir $BOOTSTRAP_PATH
-                tar -zxf $BOOTSTRAP_NAME.tar.gz -C $BOOTSTRAP_PATH
+                mkdir "$BOOTSTRAP_PATH"
+                tar -zxf "$BOOTSTRAP_NAME.tar.gz" -C "$BOOTSTRAP_PATH"
                 cd -
             else
                 warning "Downloading bootstrap failed."
                 info "Attempting to build bootstrap."
                 unset PUBLISH
-                BOOTSTRAP_SRC=$(dirname $FAB_PATH)/bootstrap
+                BOOTSTRAP_SRC=$(dirname "$FAB_PATH")/bootstrap
                 [[ "$publish" != "yes" ]] || PUBLISH="--publish"
-                $BT/bt-bootstrap $PUBLISH --no-clean --force \
+                "$BT"/bt-bootstrap $PUBLISH --no-clean --force \
                     || fatal "Building bootstrap failed... :("
-                rsync --delete -Hac $BOOTSTRAP_SRC/build/bootstrap/ \
-                    $FAB_PATH/bootstraps/$TKL_CODENAME/
+                rsync --delete -Hac "$BOOTSTRAP_SRC"/build/bootstrap/ \
+                    "$FAB_PATH"/bootstraps/$TKL_CODENAME/
                 # create symlinks so bin/generate-buildenv completes successfully
-                ln -s $BT_BUILDS/bootstrap/$BOOTSTRAP_NAME.tar.gz \
-                    $(dirname $BOOTSTRAP_PATH)/$BOOTSTRAP_NAME.tar.gz
-                ln -s $BT_BUILDS/bootstrap/$BOOTSTRAP_NAME.tar.gz.hash \
-                    $(dirname $BOOTSTRAP_PATH)/$BOOTSTRAP_NAME.tar.gz.hash
+                ln -s "$BT_BUILDS/bootstrap/$BOOTSTRAP_NAME.tar.gz" \
+                    "$(dirname "$BOOTSTRAP_PATH")/$BOOTSTRAP_NAME.tar.gz"
+                ln -s "$BT_BUILDS/bootstrap/$BOOTSTRAP_NAME.tar.gz.hash" \
+                    "$(dirname "$BOOTSTRAP_PATH")"/"$BOOTSTRAP_NAME.tar.gz.hash"
             fi
         fi
     fi
 fi
 
-cd $BT_PRODUCTS/$appname
+cd "$BT_PRODUCTS/$appname"
 if [[ -n "$use_existing" ]]; then
     ISO=build/product.iso
     [[ -f "$ISO" ]] || fatal "iso $PWD/$ISO not found"
 else
     info "Preperation done. Building appliance $appname."
-    cd $BT_PRODUCTS/$appname
+    cd "$BT_PRODUCTS/$appname"
     deck -D build/root.sandbox || true
     make clean || true
     mkdir -p build
@@ -298,7 +302,7 @@ if [[ -z "$no_screens" ]]; then
     if [[ -n "$use_existing" ]]; then
         info "Product iso being loaded as docker container"
         # TODO make dockerize output more quiet when --quiet used - workaround via tail
-        image_name=$(dockerize --quiet --iso build/product.iso --name $appname | tail -1)
+        image_name=$(dockerize --quiet --iso build/product.iso --name "$appname" | tail -1)
     else
         info "Product rootfs being loaded as docker container"
         # TODO make dockerize output more quiet when --quiet used - workaround via tail
@@ -308,11 +312,11 @@ if [[ -z "$no_screens" ]]; then
     info "Creating new product docker container from image and starting"
     app_cont_id=$(podman run -dt -p 80:80 -p 443:443 -p 12321:12321 \
                     -p 12322:12322 --tmpfs /tmp --tmpfs /run \
-                    --tmpfs /run/lock $image_name)
+                    --tmpfs /run/lock "$image_name")
     #app_ip=$(podman inspect $app_cont_id --format "{{.NetworkSettings.IPAddress}}")
 
     export TKL_SCREENSHOT_PATH=$BT_PRODUCTS/$appname/build/screens
-    mkdir -p $TKL_SCREENSHOT_PATH
+    mkdir -p "$TKL_SCREENSHOT_PATH"
     SELENIUM_CONT=docker.io/selenium/standalone-chrome
     SELENIUM_TAG=4.7.2-20221219
 
@@ -322,7 +326,7 @@ if [[ -z "$no_screens" ]]; then
     host_ip=$(hostname -I | awk '{print $1}')
     if [[ -f "$INIT_CONF" ]]; then
         info "Loading default conf and adding fqdn to selenium hosts file"
-        source $INIT_CONF
+        source "$INIT_CONF"
         [[ -n "$APP_DOMAIN" ]] || fatal "APP_DOMAIN not set, please check $INIT_CONF"
         add_hosts="--add-host=${APP_DOMAIN}:${host_ip}"
     else
@@ -340,7 +344,7 @@ if [[ -z "$no_screens" ]]; then
         info "no existing selenium container found - starting one"
         #podman container stop $existing_id >/dev/null 2>&1 || [[ $? -eq 1 ]]
         #podman container rm $existing_id >/dev/null 2>&1 || [[ $? -eq 1 ]]A
-        sel_cont_id=$(podman run -d -p 4444:4444 -p 7900:7900 $add_hosts \
+        sel_cont_id=$(podman run -d -p 4444:4444 -p 7900:7900 "$add_hosts" \
                         --shm-size="2g" $SELENIUM_CONT:$SELENIUM_TAG)
     else
         info "Local container found (id: $existing_id)"
@@ -352,7 +356,7 @@ if [[ -z "$no_screens" ]]; then
     #                    --shm-size="2g" $SELENIUM_CONT:$SELENIUM_TAG)
 
     info "waiting until container status is 'running'"
-    while [[ $(container_status $sel_cont_id) != "running" ]]; do
+    while [[ $(container_status "$sel_cont_id") != "running" ]]; do
         sleep 1
     done
     info "container running - waiting for connection"
@@ -361,7 +365,7 @@ if [[ -z "$no_screens" ]]; then
            sleep 1
         fi
         if [[ "$appname" != 'tkldev' ]]; then
-            if ! curl --insecure https://$host_ip:12321 >/dev/null 2>&1; then
+            if ! curl --insecure "https://$host_ip:12321" >/dev/null 2>&1; then
                 sleep 1
             fi
         else
@@ -388,7 +392,7 @@ if [[ -z "$no_screens" ]]; then
         exit_code=0
         info "attempt $count"
         # note TKL_SCREENSHOT_PATH exported above
-        clicksnap test $appname ${schema}://${APP_DOMAIN}/ || exit_code=$?
+        clicksnap test "$appname" "${schema}://${APP_DOMAIN}/" || exit_code=$?
         if [[ $exit_code -eq 0 ]]; then
             info "Success"
             break
@@ -400,22 +404,22 @@ if [[ -z "$no_screens" ]]; then
     [[ $exit_code -eq 0 ]] || fatal "Screenshots failed after $max_tries attempts"
 fi
 
-mkdir -p $BT_ISOS
+mkdir -p "$BT_ISOS"
 unset arg
 [[ -z "$no_screens" ]] || arg="--no-screens"
-$BT/bin/iso-release --force $arg $BT_ISOS
+"$BT/bin/iso-release" --force $arg "$BT_ISOS"
 
 if [[ "$publish" == "yes" ]]; then
     name=$(cat build/root.sandbox/etc/turnkey_version)
-    $BT/bin/iso-publish $arg $BT_ISOS/$name.iso
+    "$BT/bin/iso-publish" $arg "$BT_ISOS/$name.iso"
 fi
 
 if [[ -z "$BT_DEBUG" ]]; then
     deck -D build/root.sandbox
     make clean
     if [[ -z "$no_screens" ]]; then
-        info "stopping $appname container: $(podman stop $app_cont_id)"
-        info "removing $appname container: $(podman rm $app_cont_id)"
-        info "removing $appname image: $(podman rmi $image_name)"
+        info "stopping $appname container: $(podman stop "$app_cont_id")"
+        info "removing $appname container: $(podman rm "$app_cont_id")"
+        info "removing $appname image: $(podman rmi "$image_name")"
     fi
 fi
