fix bug where clicksnap code wasn't checked under all circumstance

diff --git a/bt-iso b/bt-iso
--- a/bt-iso
+++ b/bt-iso
@@ -219,9 +219,9 @@ if [[ -z "$skip_setup" ]]; then
                 cd -
                 touch /root/clicksnap-setup.done
             fi
-            if ! grep $appname <<<$(clicksnap list); then
-                fatal "Clicksnap code for $appname not found"
-            fi
+        fi
+        if ! grep $appname <<<$(clicksnap list); then
+            fatal "Clicksnap code for $appname not found"
         fi
     fi
 
